异步中,不能处理 try catch
所以,直接在回调中判断是否有错误 

setTimeout 时间为 0 的时候,所有同步的代码执行结束后(调用栈为空),才会运行

异步的函数不能封装为同步的